apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nextcloud
        image: ghcr.io/linuxserver/nextcloud:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: my-docker-registry